### ISSUE TITLE
Help getting started

### ISSUE THREAD

**Issue by findborg** [samuelngs/weave#1]
I have followed the directions so far up to creating the index.js page.  I am a major beginner.  I am not quite sure what to do next as far as creating the components/pages.  Is there anyway for you to give me an example.  I was looking for a test folder but you do not have one.  On a side note,  everything seemed to install just fine.  I am familiar with vue but have never used react or inferno.

**Comment by samuelngs** [comment]
Hi @findborg 

I just made a commit for the examples. And `tests` are coming. Please let me know if you need any help. 😃

**Comment by findborg** [comment]
Hey nice,
I will check it out now.

**Comment by findborg** [comment]
@samuelngs  I have it working.  I have the Hello Page example set up.  Works great under dev mode.  I even tried adding and subtracting content to those pages with success.  I ran the build script and it looks like that went good as well.  I got the dist folder with a server.js,  sw.js  /assets and /app.manafest.  Now my next question is how do I view this?  I created an index.html page and tried linking to server.js and sw.js 
I am working in localhost/70 directory.  Do I need to alter the router and add /70 to it?

**Comment by samuelngs** [comment]
@findborg 

Awesome 👍 After `npm run build`, you should be able to run `node dist/server.js`. Now open a browser window and navigate to http://localhost:5000.

If you have a route with `<Route path="/70" component={Something} />`, the page should be rendered under `http://localhost:5000/70`

**Comment by findborg** [comment]
Arghh I won't be able to use this because everything I use is on a hosted environment.   But I  did what you  said and it works perfect on my device machine.    Good job.
